import product from "../../modals/product"


const ProductsData = [
    {
        _id: "agate1",
        title: "African Agate Heart",
        price: 14,
        slug: "wholesale-african-agate",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image : "/p3.jpg",
        category : "agate",
        kg: "Sold per Kilogram",
    },
    {
        _id: "agate2",
        title: "African Agate Palm Stone",
        price: 14,
        slug: "African Agate Palm Stone",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg" ,
        category : "agate",
        kg : "Sold per Kilogram",
    },
    {
        _id: "apatite1",
        title: "Apatite Tower",
        price: 114,
        slug: "apatite-tower",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg" ,
        category : "apatite",
        kg : "Sold per Kilogram",
    },
    {
        _id: "apatite2",
        title: "Apatite Tumbled Stone",
        price: 74,
        slug: "apatite-tumbled-stone",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg" ,
        category : "apatite",
        kg : "Sold per Kilogram",
    },
    {
        _id: "apatite3",
        title: "Blue Apatite Sphere",
        price: 7,
        slug: "Blue Apatite Sphere",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg",
        category : "apatite",
        kg : "Sold per Kilogram",
    },
    
    {
        _id: "aquamarine1",
        title: "7 Chakra Pendants – Tree of Life",
        price: 4,
        slug: "7-chakra-pendants-tree-of-life",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg" ,
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
    {
        _id: "aquamarine2",
        title: "7 Chakra Tree of Life Pendant",
        price: 74,
        slug: "7-chakra-tree-of-life-pendant",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg" ,
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
    {
        _id: "aquamarine3",
        title: "Aquamarine and Clear Crystal Orgone Pyramid",
        price: 7,
        slug: "aquamarine-and-clear-crystal-orgone-pyramid",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg",
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
    {
        _id: "aquamarine4",
        title: "Aquamarine Bracelet | Chips Bracelet",
        price: 7,
        slug: "aquamarine-bracelet-chips-bracelet",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg",
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
    {
        _id: "aquamarine5",
        title: "Aquamarine Orgone Pyramid",
        price: 7,
        slug: "aquamarine-orgone-pyramid",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg",
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
    {
        _id: "aquamarine6",
        title: "Aquamarine Pendant – Spiral Wire Wrapped",
        price: 7,
        slug: "aquamarine-pendant-spiral-wire-wrapped",
        images: ["/p1" ,"/p2","/p3" ,"/p4" ],
        image :"/p3.jpg",
        category : "aquamarine",
        kg : "Sold per Kilogram",
    },
            
]

export default ProductsData;